server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: phonebook
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none